### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by cnc4less** [mcprakash/Eigen#3]
will kindly show us how to install  this library an configure with with arduino ide , 
best regards

**Comment by cnc4less** [comment]
will kindly show us how to install this library an configure with with arduino ide ,
best regards

**Comment by mcprakash** [comment]
hi cnc4less. 
 The Eigen library is too heavy for Arduino (Atmega) , but it works for Arduino (ARM like Due). Just copy paste the library into Arduino/lib. 

 Use #include "Eigen.h" and you should be all set. 
Hope it helps. 

Best
Chandra
